### ISSUE TITLE
ErrorException after update

### ISSUE THREAD

**Issue by alim-akbashev** [LeaseWeb/LswMemcacheBundle#1]
ErrorException: Runtime Notice: Declaration of Lsw\MemcacheBundle\Cache\LoggingMemcache::increment() should be compatible with Memcached::increment($key, $offset = NULL, $initial_value = NULL, $expiry = NULL) in vendor/leaseweb/memcache-bundle/Lsw/MemcacheBundle/Cache/LoggingMemcache.php line 7

PHP 5.4.6-1ubuntu1.2
php5-memcached 2.0.1-6

**Comment by hmert** [comment]
Hi,
we have following config and getting same error.
https://github.com/okulbilisim/ojs/blob/master/.travis.yml

```
[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                
  Runtime Notice: Declaration of Lsw\MemcacheBundle\Cache\LoggingMemcache::get() should be compatible with Memcached::get($key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL) 
```
https://travis-ci.org/okulbilisim/ojs/builds/47384062
