### ISSUE TITLE
Anti Dog Pile System, how to use it ?

### ISSUE THREAD

**Issue by ghisleouf** [LeaseWeb/LswMemcacheBundle#10]
I'd like to configure the bundle to use the Anti Dog-Pile system on doctrine queries, is it possible ? How can i achieve it ?

Thanks a lot.

**Comment by andrzejdziekonski** [comment]
Could you tell me how to refresh key cache if i manage to use getAdp method? Let's say i have articles query stored in $key = 'articles'. When i edit one of articles i would like to refresh my cache. Normally i would use $this->container->get('memcache.default')->delete($key) but is it OK when in adp case? Or maybe should i setAdp($key, NULL, 0, $ttl)?

**Comment by mevdschee** [comment]
Delete still works as normal, the data is stored on the same key in a different format.

**Comment by andrzejdziekonski** [comment]
So what actually happens on delete adp cache entry? Readme says "we serve the old cache entries while calculating the new value and by using an atomic read and write operation we can make sure only one thread will receive a cache miss when the content is invalidated". When i delete the key there is no "old cache entry" to serve. Is it some kind of soft delete? I would like to understand this to use this function properly.

**Comment by mevdschee** [comment]
Stale (old cache) entry will not be served anymore, when key is deleted using the delete call. Invalidating an ADP entry, so that only one thread receives a miss is currently not possible. It is not really hard to implement and it is a reasonable request. I'm willing to implement that if that's what you're after.

**Comment by andrzejdziekonski** [comment]
Sounds great!

**Comment by mevdschee** [comment]
ok.. give me a few hours :-)

**Comment by mevdschee** [comment]
Version 2.1.8, that was just released, has the added function "deleteAdp()" that you suggested. Thank you!

**Comment by andrzejdziekonski** [comment]
Thank you, works like a charm! :+1:
