### ISSUE TITLE
Сompatibility with memcached 2.2.0 (Runtime Notice)

### ISSUE THREAD

**Issue by maxim-mamonov** [LeaseWeb/LswMemcacheBundle#21]
Could you please check compatibility LswMemcacheBundle with http://pecl.php.net/package/memcached/2.2.0

```
Runtime Notice: Declaration of Lsw\MemcacheBundle\Cache\LoggingMemcache::get() should be compatible with Memcached::get($key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL)
```

I use centos 5.7, php 5.4.27 and memcached 2.2.0. When I downgraded php-pecl-memcached to 2.1.0 - bundle works greate.

**Comment by hlorridi** [comment]
if you want, i've made a "temp" fix here 
https://github.com/ingenki/memcached-bundle

```
        {
            "type" : "vcs",
            "url" : "https://github.com/ingenki/memcached-bundle"
        }
```
```
composer update ingenki/memcached-bundle:"dev-fix/runtime-error"
```

**Comment by mevdschee** [comment]
@hlorridi I appreciate the effort, thank you. I'm not sure I should merge this workaround, though. As a 'solution' I invested some time and rewrote the bundle to work with the php-memcache extension (without the 'd'). You can find the code in the 'dev' branch for now. It will be version 2, which will be a breaking change. I hope people understand why.

**Comment by hlorridi** [comment]
Hi, that's not a "fix" but just a temporary tricks. :-/

**Comment by mevdschee** [comment]
Closing this ticket as version 2 is out which uses the PHP memcache extension (not memcached) and does not have these issues.
