### ISSUE TITLE
Warning: Parameter 3 to Memcached::get() expected to be a reference

### ISSUE THREAD

**Issue by deep9** [LeaseWeb/LswMemcacheBundle#25]
Since 1.2.7, where the call was changed (https://github.com/LeaseWeb/LswMemcacheBundle/blob/v1.2.6/Cache/LoggingMemcache.php#L77) I'm getting: ContextErrorException: Warning: Parameter 3 to Memcached::get() expected to be a reference, value given in /vagrant/vendor/leaseweb/memcache-bundle/Lsw/MemcacheBundle/Cache/LoggingMemcache.php line 35.

The change is here (https://github.com/LeaseWeb/LswMemcacheBundle/blob/v1.2.7/Cache/LoggingMemcache.php#L31). By calling the forward_static_call_array('parent::get', func_get_args()) the reference is lost?

I guess all the functions using reference are affected?

Maybe this being just a warning is not important, but it throws error in our Symfony project.

**Comment by mevdschee** [comment]
The calls to 'forward_static_call_array' have been removed.
