### ISSUE TITLE
Segfaults with v1.2.15

### ISSUE THREAD

**Issue by h4cc** [LeaseWeb/LswMemcacheBundle#38]
Using the v1.2.15 release this PHP version will cause a silent segfault:

```
PHP 5.3.10-1ubuntu3.14 with Suhosin-Patch (cli) (built: Sep  4 2014 07:08:49) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with Xdebug v2.1.0, Copyright (c) 2002-2010, by Derick Rethans
```

Have not yet been abled to trace down the cause, but will update when i find it.

**Comment by mevdschee** [comment]
This bug should no longer exist due to the reverted implementation.
