### ISSUE TITLE
Sessions no longer stored in memcache

### ISSUE THREAD

**Issue by Sander-Toonen** [LeaseWeb/LswMemcacheBundle#40]
Ever since the update from v1.2.13 to v1.2.14 sessions are no longer stored in memcache by solely defining a client for lsw_memcache. This is due to the following commit: df0a643e17bf82f1dd93d790560d55ee9779b05b

In `Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension::registerSessionConfiguration()` the `session.handler` alias is always set to the session handler set at that moment. (By default this is `session.handler.native_file`). This part is executed before this bundle's `EnableSessionSupport` compiler pass and therefore the compilerpass will never set the `session.handler` alias.

Undoing that commit will however not solve all the problems. For instance, when setting a value for `metadata_update_threshold`, a session handler wrapper is defined as session handler. Without the previously mentioned commit, the `EnableSessionSupport` compiler pass will overwrite the session handler while the expected behavour is that the `WriteCheckSessionHandler` would wrap the `LockingSessionHandler`. (And even when this bundle would not overwrite the session handler, the wrong session handler would be wrapped.)

Adding the following to `config.yml` solves the entire problem:
```
services:
    session.handler:
        alias: memcache.session_handler
```
All in all I get the idea that automatic registration of `memcache.session_handler` as session handler creates more problems than it solves. At the moment, the compiler pass is actually doing nothing at all.  I believe it is better to instruct the users to explicitly set the session.handler. Its just a small step and this not only makes it clearer for the user what exactly is going on, it also lets the memcache session handler hook better into the whole environment.

**Comment by estheban** [comment]
Thanks.

**Comment by mevdschee** [comment]
This issue is addressed in v2 (currently in the dev branch)
