### ISSUE TITLE
How to use on windows without php_memcached.dll available ?

### ISSUE THREAD

**Issue by picks44** [LeaseWeb/LswMemcacheBundle#48]
I'm trying to use this on WIndows (WAMP, PHP 5.4), but after a looooong search I can't find the PHP ext memcached.dll (note the -d at the end).
Any help on how to use this bundle locally while developing on Windows ?
Thanks !

**Comment by mevdschee** [comment]
Sorry, that is currently not supported.

**Comment by mevdschee** [comment]
Just a message to notify you that version 2 of this bundle has been released and that this version has Windows support.
