### ISSUE TITLE
require memcached php extension?

### ISSUE THREAD

**Issue by dinamic** [LeaseWeb/LswMemcacheBundle#5]
I've tried to install the bundle, but it seems the memcached php extension is a requirement.

What about the users of a shared hosting that does not provide memcached extension?

IMHO this should be a suggestion rather than requirement.

The requirement has to be set for the ext-memcache, which provides the Memcache class.

```
> composer require leaseweb/memcache-bundle dev-master
composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for leaseweb/memcache-bundle dev-master -> satisfiable by leaseweb/memcache-bundle dev-master.
    - leaseweb/memcache-bundle dev-master requires ext-memcached >=1.0 -> the requested PHP extension memcached is missing from your system.


Installation failed, reverting composer.json to its original content.
```

**Comment by mevdschee** [comment]
Just a message to notify you that version 2 of this bundle has been released and that this version has Windows support.
