### ISSUE TITLE
Support for Symfony 3

### ISSUE THREAD

**Issue by JHGitty** [LeaseWeb/LswMemcacheBundle#64]
This bundle should get support for Symfony3.

**Comment by jimaek** [comment]
I am curious what are your plans for Symfony 3 support?

**Comment by JHGitty** [comment]
Currently this bundle only supports ``symfony/framework-bundle`` in version ``^2.1``. Anybody could add support to this bundle, feel free. :+1:

**Comment by mevdschee** [comment]
Yes.. please do, it will be merged!

**Comment by jimaek** [comment]
https://github.com/LeaseWeb/LswMemcacheBundle/pull/67

**Comment by mevdschee** [comment]
Thank you!!! Awesome..
