### ISSUE TITLE
enable memcached extensions

### ISSUE THREAD

**Issue by LeniA1** [LeaseWeb/LswMemcacheBundle#69]
Hi guys,

I would like store my datas on a remote server.
Do I have to install memcache on all my webservers ? composers says so ... :(

**Comment by mevdschee** [comment]
You install the client (php5-memcache) on all webservers (as suggested). Where you install the server (memcached) is up to you.

**Comment by mevdschee** [comment]
It is not a bad idea to run memcached locally on your webservers, because it will be very low latency that way, but it is not mandatory.

Shall I close the issue?

**Comment by LeniA1** [comment]
Yes all good,  thank you very much for this very clear explonation !

**Comment by mevdschee** [comment]
You are welcome, enjoy the software!
