### ISSUE TITLE
Fix debug.yml for Symfony3 compatible

### ISSUE THREAD

**Issue by bubnovKelnik** [LeaseWeb/LswMemcacheBundle#83]
Not quoting the scalar "%memcache.data_collector.class%" and "%memcache.data_collector.template%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0

Already have the PR: https://github.com/LeaseWeb/LswMemcacheBundle/pull/82

**Comment by GabrielAnca** [comment]
Thanks for your contribution! This issue is closed as PR #82 is merged :smiley:
