### ISSUE TITLE
PHP7 memchached is not supported

### ISSUE THREAD

**Issue by kironet** [LeaseWeb/LswMemcacheBundle#86]
Hey, 

what should I install to use this bundle with php7 if php7 doesn't support memcached?

Thanks

**Comment by mevdschee** [comment]
It is available now, just run `apt install php-memcached`, that will do it.

**Comment by kironet** [comment]
I'm using centos and still see this error.

pecl/memcached requires PHP (version >= 5.2.0, version <= 6.0.0, excluded versions: 6.0.0), installed version is 7.0.13

**Comment by GabrielAnca** [comment]
Hi!

Apparently php7 support is not available in the memcached pecl packages yet. However, this seems to work: https://github.com/php-memcached-dev/php-memcached/tree/php7

Here you can find how to install it: https://github.com/ChiVincent/php-7-centos/blob/master/memcached.sh

**Comment by mevdschee** [comment]
AFAIK this bundle no longer uses `pecl/memcached`, it uses `pecl/memcache`.

**Comment by kironet** [comment]
Oh, then I should uninstall memcached and install memcache. Thanks

**Comment by mevdschee** [comment]
Use this howto: http://boomshadow.net/tech/installs/how-to-install-php-memcache/

Use this source: https://github.com/websupport-sk/pecl-memcache/tree/NON_BLOCKING_IO_php7
